global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using System.Collections.ObjectModel;
global using FunctionalExtensions.Base;
global using FunctionalExtensions.Base.Results;
global using static FunctionalExtensions.Base.UnitExtensions;
global using static FunctionalExtensions.Base.Try;
global using static FunctionalExtensions.Base.Disposing;