
PROJECT_NAME=${1:-Janus.Mask.Sqlite.WebApp}
NODE_ID="${NODE_ID:-SqliteMaskNode1}"
LISTEN_PORT="${LISTEN_PORT:-30001}"
TIMEOUT_MS="${TIMEOUT_MS:-5000}"
COMMUNICATION_FORMAT="${COMMUNICATION_FORMAT:-AVRO}"
NETWORK_ADAPTER_TYPE="${NETWORK_ADAPTER_TYPE:-TCP}"
EAGER_STARTUP="${EAGER_STARTUP:-true}"
STARTUP_REMOTE_POINTS="${STARTUP_REMOTE_POINTS:-}"
STARTUP_NODE_SCHEMA_LOAD="${STARTUP_NODE_SCHEMA_LOAD:-}"
STARTUP_MATERIALIZE_DATABASE="${STARTUP_MATERIALIZE_DATABASE:-true}"
MATERIALIZATION_CONNECTION_STRING="${MATERIALIZATION_CONNECTION_STRING:-./materialization.db}"
PERSISTENCE_CONNECTION_STRING="${PERSISTENCE_CONNECTION_STRING:-./mask_database.db}"

WEB_PORT="${WEB_PORT:-8013}"

STARTUP_REMOTE_POINTS=$(bash /Scripts/reformat_remote_points.sh ${STARTUP_REMOTE_POINTS})

envsubst < /App/appsettings.json.template | sed -e 's/§/$/g' > /App/appsettings.json

env
cat /App/appsettings.json

exec /App/${PROJECT_NAME}