
PROJECT_NAME=${1:-Janus.Mask.WebApi.WebApp}
NODE_ID="${NODE_ID:-MaskNode1}"
LISTEN_PORT="${LISTEN_PORT:-30001}"
TIMEOUT_MS="${TIMEOUT_MS:-5000}"
COMMUNICATION_FORMAT="${COMMUNICATION_FORMAT:-AVRO}"
NETWORK_ADAPTER_TYPE="${NETWORK_ADAPTER_TYPE:-TCP}"
EAGER_STARTUP="${EAGER_STARTUP:-true}"
STARTUP_REMOTE_POINTS="${STARTUP_REMOTE_POINTS:-}"
STARTUP_NODE_SCHEMA_LOAD="${STARTUP_NODE_SCHEMA_LOAD:-}"
STARTUP_WEB_API="${STARTUP_WEB_API:-true}"
PERSISTENCE_CONNECTION_STRING="${PERSISTENCE_CONNECTION_STRING:-./mask_database.db}"
WEB_API_LISTEN_PORT="${WEB_API_LISTEN_PORT:-8801}"
WEB_API_USE_SSL="${WEB_API_USE_SSL:-False}"
WEB_API_LISTEN_PORT_SECURE="${WEB_API_LISTEN_PORT_SECURE:-8802}"
WEB_PORT="${WEB_PORT:-8013}"

STARTUP_REMOTE_POINTS=$(bash /Scripts/reformat_remote_points.sh ${STARTUP_REMOTE_POINTS})

envsubst < /App/appsettings.json.template | sed -e 's/§/$/g' > /App/appsettings.json

env
cat /App/appsettings.json

exec /App/${PROJECT_NAME}