#!/bin/bash

PROJECT_NAME="${1:-Janus.Mediator.WebApp}"
COMPONENT_TYPE="${COMPONENT_TYPE:-Mediator}"
NODE_ID="${NODE_ID:-Mediator1}"
LISTEN_PORT="${LISTEN_PORT:-20001}"
TIMEOUT_MS="${TIMEOUT_MS:-5000}"
COMMUNICATION_FORMAT="${COMMUNICATION_FORMAT:-AVRO}"
NETWORK_ADAPTER_TYPE="${NETWORK_ADAPTER_TYPE:-TCP}"
EAGER_STARTUP="${EAGER_STARTUP:-true}"
STARTUP_REMOTE_POINTS="${STARTUP_REMOTE_POINTS:-}"
STARTUP_NODES_SCHEMA_LOAD="${STARTUP_NODES_SCHEMA_LOAD:-}"
STARTUP_MEDIATION_SCRIPT="${STARTUP_MEDIATION_SCRIPT:-}"
PERSISTENCE_CONNECTION_STRING="${PERSISTENCE_CONNECTION_STRING:-./mediator_database.db}"
WEB_PORT="${WEB_PORT:-8101}"

STARTUP_REMOTE_POINTS=$(bash /Scripts/reformat_remote_points.sh ${STARTUP_REMOTE_POINTS})
STARTUP_NODES_SCHEMA_LOAD=$(bash /Scripts/reformat_node_ids.sh ${STARTUP_NODES_SCHEMA_LOAD})

envsubst < /App/appsettings.json.template | sed -e 's/§/$/g' > /App/appsettings.json

env
cat /App/appsettings.json

exec /App/${PROJECT_NAME}